name: C-Exec Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            OUTPUT: c
          - os: windows-latest
            OUTPUT: c.exe

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Nim environment
        uses: jiro4989/setup-nim-action@v1.1.4
      
      - name: Install Nim dependencies
        run: nimble -y install shlex regex

      - name: Compile c
        run: nim -d:release c c.nim
        
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./${{ matrix.OUTPUT }}
          asset_name: ${{ matrix.OUTPUT }}
          tag: ${{ github.ref }}
          overwrite: true
          body: "The latest release."
